// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartialUsd } from "./PartialUsd";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Cost-basis accounting for a scope (ACCOUNTING.md §4–§6).
 */
export type AccountingSummary = {
  unrealized_pnl_usd: string | null;
  unrealized_return_percent: string | null;
  unrealized_reason: UnavailableReason | null;
  /**
   * Remaining basis when every lot's basis is known.
   */
  remaining_basis_usd: string | null;
  /**
   * P&L of the lots whose basis is known, valued at their own quantity only.
   */
  known_subset_value_usd: string;
  known_subset_basis_usd: string;
  known_subset_pnl_usd: string;
  known_subset_return_percent: string | null;
  /**
   * Share of the valued holdings whose basis is known, in percent.
   */
  basis_coverage_percent: string | null;
  has_estimated_basis: boolean;
  realized: PartialUsd;
  income: PartialUsd;
  expenses: PartialUsd;
  /**
   * Unrealized + realized + income - expenses, only when every part is complete.
   */
  total_accounted_pnl_usd: string | null;
  fee_charges: number;
  /**
   * Movements waiting for a user decision (basis, classification, proceeds, price).
   */
  review_count: number;
  /**
   * Inventory gaps, balance mismatches and other reconciliation findings.
   */
  reconciliation_count: number;
};
