// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coverage } from "./Coverage";

/**
 * Synchronization state of one account for the UI.
 */
export type AccountSyncStatus = {
  fallback_reasons: Array<string>;
  balance_only: boolean;
  account_id: string;
  provider: string | null;
  coverage: Coverage | null;
  last_attempt_at: number | null;
  last_success_at: number | null;
  last_error: string | null;
  earliest_covered_at: number | null;
  transaction_count: number;
  pending_incomplete: boolean;
};
