// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkId } from "./NetworkId";

export type Account = {
  id: string;
  wallet_id: string;
  network: NetworkId;
  canonical_address: string;
  display_address: string;
  label: string | null;
  archived: boolean;
  created_at: number;
};
