// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coverage } from "./Coverage";

export type AccountCoverage = {
  provider: string;
  category: string;
  coverage: Coverage;
  earliest_covered_at: number | null;
  updated_at: number;
};
