// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coverage } from "./Coverage";
import type { NetworkId } from "./NetworkId";

/**
 * Result of synchronizing one account.
 */
export type AccountSyncReport = {
  fallback_reasons: Array<string>;
  balance_only: boolean;
  account_id: string;
  network: NetworkId;
  provider: string | null;
  balance_refreshed: boolean;
  new_transactions: number;
  pages_fetched: number;
  coverage: Coverage;
  error: string | null;
};
