// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityLeg = {
  leg_id: string;
  asset_id: string;
  symbol: string | null;
  signed_quantity: string;
  direction: string;
  /**
   * How the accounting replay interpreted this movement.
   */
  treatment: string | null;
  /**
   * Historical USD value at the time of the movement, if a quote exists.
   */
  value_usd: string | null;
  value_estimated: boolean;
  review: string | null;
};
