// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityRow } from "./ActivityRow";

export type ActivityPage = {
  rows: Array<ActivityRow>;
  /**
   * Opaque keyset cursor for the next page.
   */
  next_cursor: string | null;
};
