// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityLeg } from "./ActivityLeg";
import type { NetworkId } from "./NetworkId";

export type ActivityRow = {
  transaction_id: string;
  account_id: string;
  network: NetworkId;
  occurred_at: number;
  operation: string;
  status: string;
  legs: Array<ActivityLeg>;
  fee_quantity: string | null;
  fee_symbol: string | null;
  fee_value_usd: string | null;
  unresolved: boolean;
};
