// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkId } from "./NetworkId";

/**
 * Optional activity filters (SPECIFICATION.md §5.6).
 */
export type ActivityFilter = {
  asset_id: string | null;
  /**
   * Only movements that need review or are not fully decoded.
   */
  unresolved_only: boolean;
  account_id: string | null;
  network: NetworkId | null;
  operation: string | null;
  status: string | null;
  start: number | null;
  end: number | null;
};
