// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileKind } from "./ProfileKind";

export type AppInfo = {
  product_name: string;
  version: string;
  profile: ProfileKind;
  schema_version: number;
  accounting_engine_version: number;
  data_directory: string;
};
