// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visibility is independent from accounting inclusion. None follows provider spam classification.
 */
export type AssetPolicy = {
  asset_id: string;
  symbol: string | null;
  name: string | null;
  verification: string;
  hidden: boolean;
  exclude_override: boolean | null;
};
