// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartSeries } from "./ChartSeries";
import type { PricePoint } from "./PricePoint";

/**
 * Market price and holdings value of one asset: two different series.
 */
export type AssetChart = { price: Array<PricePoint>; holdings: ChartSeries };
