// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceStatus } from "./BalanceStatus";
import type { BasisCoverage } from "./BasisCoverage";

/**
 * An asset's position in one account of the scope.
 */
export type AssetAccountRow = {
  account_id: string;
  wallet_id: string;
  quantity: string;
  value_usd: string | null;
  basis_usd: string | null;
  unrealized_pnl_usd: string | null;
  basis_coverage: BasisCoverage;
  balance_status: BalanceStatus;
};
