// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAccountRow } from "./AssetAccountRow";
import type { LotRow } from "./LotRow";
import type { NetworkId } from "./NetworkId";
import type { PartialUsd } from "./PartialUsd";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Asset detail for a scope (SPECIFICATION.md §5.4).
 */
export type AssetDetail = {
  asset_id: string;
  network: NetworkId;
  /**
   * Contract, mint or master address; `None` for the native asset.
   */
  contract: string | null;
  symbol: string | null;
  name: string | null;
  decimals: number;
  verification: string;
  explorer_url: string | null;
  price_usd: string | null;
  price_observed_at: number | null;
  change_24h_percent: string | null;
  quantity: string;
  value_usd: string | null;
  remaining_basis_usd: string | null;
  unrealized_pnl_usd: string | null;
  unrealized_return_percent: string | null;
  unrealized_reason: UnavailableReason | null;
  known_subset_pnl_usd: string;
  basis_coverage_quantity_percent: string | null;
  has_estimated_basis: boolean;
  realized: PartialUsd;
  income: PartialUsd;
  expenses: PartialUsd;
  accounts: Array<AssetAccountRow>;
  lots: Array<LotRow>;
};
