// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness of the latest balance observation.
 */
export type BalanceStatus = "fresh" | "stale" | "missing" | "conflicted";
