// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Certainty of a lot's acquisition basis.
 */
export type BasisKind = "known" | "estimated" | "unknown";
