// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisKind } from "./BasisKind";

/**
 * One acquisition fragment attached to a receipt (basis correction or CSV).
 */
export type BasisLotInput = {
  /**
   * Exact decimal asset units.
   */
  quantity: string;
  /**
   * Exact USD; `None` means unknown, `"0"` an explicit zero.
   */
  basis_usd: string | null;
  basis_kind: BasisKind;
  /**
   * Original acquisition time (may precede the on-chain receipt).
   */
  acquired_at: number;
};
