// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a position's acquisition basis is known.
 */
export type BasisCoverage = "known" | "estimated" | "partial" | "unknown";
