// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartPoint } from "./ChartPoint";
import type { ChartRange } from "./ChartRange";
import type { PeriodPerformanceDto } from "./PeriodPerformanceDto";

export type ChartSeries = {
  range: ChartRange;
  interval_seconds: number;
  points: Array<ChartPoint>;
  /**
   * Earliest time with usable data in this scope, if any.
   */
  history_available_since: number | null;
  /**
   * Flow-adjusted performance over the displayed interval.
   */
  performance: PeriodPerformanceDto | null;
};
