// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartPoint = {
  t: number;
  /**
   * `None` marks a gap; the chart must not connect across it.
   */
  value_usd: string | null;
  /**
   * Daily or otherwise coarse prices were used for this point.
   */
  estimated: boolean;
  /**
   * Some held assets had no usable price; the value covers a subset.
   */
  partial: boolean;
};
