// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandError = {
  /**
   * Stable machine-readable code for the UI to localize.
   */
  code: string;
  message: string;
  /**
   * Optional related entity (e.g. the existing account for a duplicate address).
   */
  detail: string | null;
};
