// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A history category read by the adapter.
 */
export type HistoryCategory = "native" | "tokens" | "trades" | "failed" | "internal" | "pending";
