// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceStatus } from "./BalanceStatus";
import type { BasisCoverage } from "./BasisCoverage";
import type { NetworkId } from "./NetworkId";

/**
 * One chain-specific asset held within the selected scope.
 */
export type HoldingRow = {
  asset_id: string;
  network: NetworkId;
  symbol: string | null;
  name: string | null;
  verification: string;
  quantity: string;
  /**
   * `None` when no usable quote exists. Never rendered as $0.
   */
  price_usd: string | null;
  value_usd: string | null;
  change_24h_percent: string | null;
  price_observed_at: number | null;
  allocation_percent: string | null;
  balance_status: BalanceStatus;
  observed_at: number;
  /**
   * Remaining cost basis when known for the whole position.
   */
  basis_usd: string | null;
  unrealized_pnl_usd: string | null;
  unrealized_return_percent: string | null;
  basis_coverage: BasisCoverage;
};
