// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisKind } from "./BasisKind";
import type { ImportRowStatus } from "./ImportRowStatus";
import type { LegClassification } from "./LegClassification";

export type ImportRowPreview = {
  /**
   * 1-based data row (the header is row 0).
   */
  row: number;
  external_row_id: string | null;
  status: ImportRowStatus;
  messages: Array<string>;
  /**
   * Matched receipt or movement, or `None` for opening lots and errors.
   */
  leg_id: string | null;
  account_id: string | null;
  asset_id: string | null;
  quantity: string | null;
  total_basis_usd: string | null;
  basis_kind: BasisKind | null;
  acquired_at: number | null;
  classification: LegClassification | null;
  opening: boolean;
};
