// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplayReport } from "./ReplayReport";

export type ImportResult = { batch_id: string; applied_rows: number; replay: ReplayReport };
