// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportRowPreview } from "./ImportRowPreview";
import type { RecalcSummary } from "./RecalcSummary";

export type ImportPreview = {
  batch_id: string;
  file_name: string;
  file_sha256: string;
  /**
   * The identical file was already committed.
   */
  duplicate_file: boolean;
  columns: Array<string>;
  /**
   * Field -> column header actually used.
   */
  mapping: { [key in string]: string };
  missing_required: Array<string>;
  rows: Array<ImportRowPreview>;
  ok_count: number;
  error_count: number;
  duplicate_count: number;
  /**
   * Committing is possible only without errors and with something to apply.
   */
  can_commit: boolean;
  before: RecalcSummary;
  after: RecalcSummary;
};
