// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user says an unpaired movement was.
 */
export type LegClassification =
  | "deposit"
  | "reward"
  | "withdrawal"
  | "gift"
  | "own_untracked"
  | "sale"
  | "payment"
  | "unclassified";
