// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisKind } from "./BasisKind";
import type { LegOverride } from "./LegOverride";
import type { NetworkId } from "./NetworkId";
import type { OverrideVersion } from "./OverrideVersion";
import type { PairCandidate } from "./PairCandidate";

/**
 * Everything known about one movement, for the detail drawer and editor.
 */
export type LegDetail = {
  leg_id: string;
  transaction_id: string;
  tx_hash: string;
  tx_status: string;
  block_height: number | null;
  provider: string;
  explorer_url: string | null;
  account_id: string;
  network: NetworkId;
  occurred_at: number;
  asset_id: string;
  symbol: string | null;
  quantity: string;
  direction: string;
  operation: string;
  treatment: string | null;
  counterparty_account_id: string | null;
  value_usd: string | null;
  value_estimated: boolean;
  basis_usd: string | null;
  basis_kind: BasisKind | null;
  proceeds_usd: string | null;
  review: string | null;
  current: LegOverride | null;
  history: Array<OverrideVersion>;
  pair_candidates: Array<PairCandidate>;
};
