// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisLotInput } from "./BasisLotInput";
import type { LegClassification } from "./LegClassification";

/**
 * A versioned user decision about one leg. Empty fields keep the default
 * interpretation; saving an empty override reverts to it.
 */
export type LegOverride = {
  classification: LegClassification | null;
  /**
   * Acquisition lots for a receipt. Their quantity may be below the receipt;
   * the rest keeps unknown basis.
   */
  basis_lots: Array<BasisLotInput> | null;
  /**
   * Use the receipt-time market value as an *estimated* basis.
   */
  basis_from_market: boolean;
  /**
   * Gross proceeds of a sale/payment in USD.
   */
  proceeds_usd: string | null;
  /**
   * Use the market value at disposal time as estimated proceeds.
   */
  proceeds_from_market: boolean;
  /**
   * Historical unit price override for this leg's valuation.
   */
  price_usd: string | null;
  /**
   * Incoming leg of another owned account that received this outgoing leg.
   */
  pair_with: string | null;
  note: string | null;
};
