// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisKind } from "./BasisKind";

/**
 * One remaining (or historical) FIFO lot.
 */
export type LotRow = {
  id: string;
  account_id: string;
  quantity: string;
  remaining_quantity: string;
  basis_usd: string | null;
  remaining_basis_usd: string | null;
  basis_kind: BasisKind;
  /**
   * Original acquisition time (kept through own transfers).
   */
  acquired_at: number;
  /**
   * When the inventory entered this account.
   */
  arrived_at: number;
  parent_lot_id: string | null;
};
