// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkRequest = {
  id: number;
  started_at_ms: number;
  provider: string;
  method: string;
  /**
   * Only the URL origin; no credential path, query, fragment or username.
   */
  origin: string;
  /**
   * Compile-time adapter operation name, never a request body or URL path.
   */
  operation: string;
  attempt: number;
  status: string;
  http_status: number | null;
  rpc_code: number | null;
  duration_ms: number | null;
};
