// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A supported mainnet. Testnets are separate configurations and never enter a
 * mainnet portfolio total, so they are deliberately absent here.
 */
export type NetworkId =
  | "bitcoin"
  | "ethereum"
  | "base"
  | "arbitrum"
  | "optimism"
  | "polygon"
  | "bsc"
  | "solana"
  | "tron"
  | "ton";
