// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryCategory } from "./HistoryCategory";
import type { NetworkId } from "./NetworkId";
import type { Support } from "./Support";

export type NetworkCapability = {
  fallback_providers: Array<string>;
  network: NetworkId;
  provider: string;
  /**
   * The source needs an API key in this build.
   */
  key_required: boolean;
  balances: Support;
  token_discovery: Support;
  history: Array<HistoryCategory>;
  fees: Support;
  internal_transfers: Support;
  /**
   * Limitation codes; the UI explains each one.
   */
  limitations: Array<string>;
  /**
   * Date of the last successful live check recorded in the repository's
   * test report (`docs/NETWORK_COVERAGE.md`), if any.
   */
  live_verified_on: string | null;
};
