// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Address/transaction model shared by a set of networks.
 */
export type NetworkFamily = "bitcoin" | "evm" | "solana" | "tron" | "ton";
