// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkFamily } from "./NetworkFamily";
import type { NetworkId } from "./NetworkId";

export type NetworkInfo = {
  id: NetworkId;
  name: string;
  family: NetworkFamily;
  native_symbol: string;
  evm_chain_id: number | null;
};
