// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkId } from "./NetworkId";

/**
 * Result of validating one public address for one network.
 */
export type NormalizedAddress = {
  network: NetworkId;
  /**
   * Representation used for identity comparison and storage uniqueness.
   */
  canonical: string;
  /**
   * Representation shown to the user (e.g. EIP-55 checksummed for EVM).
   */
  display: string;
};
