// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasisKind } from "./BasisKind";

/**
 * Opening inventory at a declared history start (CSV `opening` rows).
 */
export type OpeningLot = {
  account_id: string;
  asset_id: string;
  quantity: string;
  basis_usd: string | null;
  basis_kind: BasisKind;
  acquired_at: number;
  /**
   * History of this account and asset before this instant is replaced by the lot.
   */
  cutoff_at: number;
  note: string | null;
};
