// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegOverride } from "./LegOverride";

/**
 * One saved version of a user decision (audit trail).
 */
export type OverrideVersion = {
  version: number;
  created_at: number;
  /**
   * `manual` or `csv:<batch>`.
   */
  source: string;
  payload: LegOverride;
  orphaned: boolean;
};
