// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkId } from "./NetworkId";

export type PairCandidate = {
  leg_id: string;
  account_id: string;
  network: NetworkId;
  occurred_at: number;
  quantity: string;
  transaction_id: string;
};
