// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A USD sum whose components may be partially unknown.
 */
export type PartialUsd = {
  /**
   * Sum of the components that are known.
   */
  known_usd: string;
  /**
   * False when at least one component is missing; the total is then not shown as complete.
   */
  complete: boolean;
};
