// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Modified Dietz performance between the first and last valued chart points.
 */
export type PeriodPerformanceDto = {
  start: number;
  end: number;
  beginning_value_usd: string;
  ending_value_usd: string;
  /**
   * Net external flows (inflows positive) that are known.
   */
  net_flows_usd: string;
  flow_count: number;
  gain_usd: string | null;
  return_percent: string | null;
  reason: UnavailableReason | null;
  /**
   * Endpoint values or flows use daily (estimated) prices.
   */
  estimated: boolean;
};
