// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountingSummary } from "./AccountingSummary";
import type { UnavailableReason } from "./UnavailableReason";

export type PortfolioSummary = {
  /**
   * Sum of valued holdings; `None` means "Value unavailable", not zero.
   */
  total_value_usd: string | null;
  holding_count: number;
  unpriced_count: number;
  stale_count: number;
  excluded_spam_count: number;
  unrealized_pnl_usd: string | null;
  unrealized_return_percent: string | null;
  unrealized_reason: UnavailableReason | null;
  last_successful_sync_at: number | null;
  account_count: number;
  accounting: AccountingSummary;
};
