// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PriceReport = {
  priced: number;
  /**
   * Asset IDs with no usable quote (shown as "price unavailable").
   */
  unpriced: Array<string>;
  errors: Array<string>;
};
