// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of downloading daily historical prices.
 */
export type PriceHistoryReport = {
  requests: number;
  points: number;
  /**
   * Assets that still need older or newer daily history after this run.
   */
  pending_assets: number;
  /**
   * Assets the provider has no series for (shown as unpriced in the past).
   */
  unavailable: Array<string>;
  errors: Array<string>;
};
