// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PricePoint = {
  t: number;
  /**
   * `None` marks a gap: no quote within tolerance.
   */
  price_usd: string | null;
  estimated: boolean;
};
