// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which local database is open. Demo data never shares a file with real data.
 */
export type ProfileKind = "real" | "demo" | "test";
