// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyRequirement } from "./KeyRequirement";
import type { KeyStorage } from "./KeyStorage";
import type { NetworkId } from "./NetworkId";
import type { ProviderRole } from "./ProviderRole";

export type ProviderStatus = {
  id: string;
  name: string;
  role: ProviderRole;
  key_requirement: KeyRequirement;
  networks: Array<NetworkId>;
  docs_url: string;
  key_url: string | null;
  free_allowance: string;
  /**
   * `None` when no key is stored. A stored key is never returned.
   */
  key_storage: KeyStorage | null;
  /**
   * Requests counted by this app today (UTC); other apps sharing the key are not included.
   */
  requests_today: number;
  estimated_credits_today: number;
  last_error: string | null;
  /**
   * Adapter availability in this build.
   */
  adapter_available: boolean;
};
