// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderRole =
  "market_prices" | "account_data" | "supplemental_prices" | "supplemental";
