// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact totals used to preview the effect of an import before committing it.
 */
export type RecalcSummary = {
  realized_known_usd: string;
  realized_complete: boolean;
  remaining_known_basis_usd: string;
  unknown_basis_lots: number;
  review_items: number;
  inventory_gaps: number;
};
