// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReconciliationRow = {
  id: string;
  /**
   * `inventory_gap`, `balance_mismatch`, `opening_overlap`,
   * `orphaned_override` or `invalid_pairing`.
   */
  kind: string;
  account_id: string | null;
  asset_id: string | null;
  symbol: string | null;
  quantity: string | null;
  detail: string;
};
