// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";

export type RemovalPreview = {
  account: Account;
  /**
   * Conservative dependency set: ownership changes may affect any account on this network.
   */
  related_accounts: Array<Account>;
  movements: number;
  fees: number;
  transactions: number;
  decisions: number;
  revision: string;
};
