// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a replay, reported to the UI and tests.
 */
export type ReplayReport = {
  events: number;
  lots: number;
  review_items: number;
  reconciliation_items: number;
  orphaned_overrides: number;
};
