// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkId } from "./NetworkId";

/**
 * A movement that needs a user decision.
 */
export type ReviewItem = {
  leg_id: string;
  transaction_id: string;
  account_id: string;
  network: NetworkId;
  occurred_at: number;
  asset_id: string;
  symbol: string | null;
  quantity: string;
  treatment: string;
  /**
   * `unknown_basis`, `unclassified_outgoing`, `missing_proceeds`,
   * `missing_price` or `missing_trade_value`.
   */
  reason: string;
  value_usd: string | null;
};
