// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReconciliationRow } from "./ReconciliationRow";
import type { ReviewItem } from "./ReviewItem";

export type ReviewList = {
  items: Array<ReviewItem>;
  /**
   * Items in scope; `items` may be truncated to the requested limit.
   */
  total: number;
  reconciliation: Array<ReconciliationRow>;
};
