// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The accounts a view covers. Overlapping selections are deduplicated.
 */
export type Scope =
  | { kind: "all" }
  | { kind: "wallet"; id: string }
  | { kind: "group"; id: string }
  | { kind: "accounts"; ids: Array<string> };
