// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemePreference } from "./ThemePreference";

export type Settings = {
  /**
   * `None` follows the operating system language.
   */
  language: string | null;
  theme: ThemePreference;
  /**
   * IANA timezone override; `None` follows the operating system.
   */
  timezone: string | null;
  privacy_mode: boolean;
  price_refresh_seconds: number;
  sweep_interval_minutes: number;
};
