// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSyncReport } from "./AccountSyncReport";
import type { PriceHistoryReport } from "./PriceHistoryReport";
import type { PriceReport } from "./PriceReport";
import type { ReplayReport } from "./ReplayReport";

export type SyncSummary = {
  accounts: Array<AccountSyncReport>;
  prices: PriceReport;
  price_history: PriceHistoryReport;
  /**
   * `None` when nothing changed since the last accounting replay.
   */
  accounting: ReplayReport | null;
  accounting_error: string | null;
};
