// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDetails } from "./SyncDetails";

export type SyncProgress = { running: boolean; cancel_requested: boolean; details: SyncDetails };
