// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncDetails = {
  active_account: string | null;
  completed_accounts: number;
  total_accounts: number;
  pages_fetched: number;
  phase: string;
};
