// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncJob = {
  id: string;
  status: string;
  error_code: string | null;
  created_at: number;
  finished_at: number | null;
};
