// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a metric is not shown as a number.
 */
export type UnavailableReason =
  | "missing_price"
  | "missing_basis"
  | "zero_basis"
  | "zero_duration"
  | "nonpositive_denominator"
  | "incomplete_classification";
