// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Wallet = {
  id: string;
  label: string;
  archived: boolean;
  created_at: number;
  account_count: number;
};
